---
name: License Check

on:
  push:
    branches:
      - main
    paths:
      - pubspec.yaml
      - .github/workflows/license_check.yaml
  pull_request:
    paths:
      - pubspec.yaml
      - .github/workflows/license_check.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  license_check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/license_check.yml@v1
    with:
      dart_sdk: 3.4.3
      allowed: MIT,BSD-3-Clause,BSD-2-Clause,Apache-2.0
      runs_on: ubuntu-22.04
